
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = 
 		[
   		"sophisticatedbackpacks:advanced_restock_upgrade|true", 
   		"sophisticatedbackpacks:tank_upgrade|true", 
     		"sophisticatedbackpacks:filter_upgrade|true", 
       		"sophisticatedbackpacks:feeding_upgrade|false", 
	 	"sophisticatedbackpacks:smoking_upgrade|false", 
   		"sophisticatedbackpacks:everlasting_upgrade|false", 
     		"sophisticatedbackpacks:advanced_feeding_upgrade|false", 
       		"sophisticatedbackpacks:crafting_upgrade|true", 
	 	"sophisticatedbackpacks:stack_upgrade_tier_4|false", 
   		"sophisticatedbackpacks:stack_upgrade_tier_2|false", 
     		"sophisticatedbackpacks:stack_upgrade_tier_3|false", 
       		"sophisticatedbackpacks:stack_upgrade_tier_1|false", 
	 	"sophisticatedbackpacks:advanced_pump_upgrade|false", 
   		"sophisticatedbackpacks:refill_upgrade|true", 
     		"sophisticatedbackpacks:auto_blasting_upgrade|false", 
       		"sophisticatedbackpacks:advanced_tool_swapper_upgrade|true", 
	 	"sophisticatedbackpacks:smelting_upgrade|false", 
   		"sophisticatedbackpacks:battery_upgrade|true", 
     		"sophisticatedbackpacks:advanced_magnet_upgrade|true", 
       		"sophisticatedbackpacks:deposit_upgrade|true", 
	 	"sophisticatedbackpacks:stonecutter_upgrade|false", 
   		"sophisticatedbackpacks:backpack|true", 
     		"sophisticatedbackpacks:jukebox_upgrade|false", 
       		"sophisticatedbackpacks:advanced_filter_upgrade|true", 
	 	"sophisticatedbackpacks:anvil_upgrade|false", 
   		"sophisticatedbackpacks:xp_pump_upgrade|false", 
     		"sophisticatedbackpacks:upgrade_base|true", 
       		"sophisticatedbackpacks:copper_backpack|true", 
	 	"sophisticatedbackpacks:advanced_deposit_upgrade|true", 
   		"sophisticatedbackpacks:restock_upgrade|true", 
     		"sophisticatedbackpacks:pump_upgrade|false", 
       		"sophisticatedbackpacks:compacting_upgrade|true", 
	 	"sophisticatedbackpacks:diamond_backpack|true", 
   		"sophisticatedbackpacks:auto_smoking_upgrade|false", 
     		"sophisticatedbackpacks:stack_upgrade_starter_tier|false", 
       		"sophisticatedbackpacks:advanced_compacting_upgrade|true", 
	 	"sophisticatedbackpacks:advanced_pickup_upgrade|true", 
   		"sophisticatedbackpacks:void_upgrade|true", 
     		"sophisticatedbackpacks:advanced_refill_upgrade|true", 
       		"sophisticatedbackpacks:magnet_upgrade|true", 
	 	"sophisticatedbackpacks:blasting_upgrade|false", 
   		"sophisticatedbackpacks:iron_backpack|true", 
     		"sophisticatedbackpacks:tool_swapper_upgrade|true", 
       		"sophisticatedbackpacks:inception_upgrade|false", 
	 	"sophisticatedbackpacks:auto_smelting_upgrade|false", 
   		"sophisticatedbackpacks:pickup_upgrade|true", 
     		"sophisticatedbackpacks:gold_backpack|true", 
       		"sophisticatedbackpacks:advanced_void_upgrade|true", 
	 	"sophisticatedbackpacks:netherite_backpack|true"
   		]

