let addBlockTags = (/** @type {TagEvent.Block} */ event) => {
    tfcStone.forEach((stone) => {
        event.add("tfc:can_collapse", 
            [
                `tfc:rock/cobble/${stone}_stairs`,
                `tfc:rock/cobble/${stone}_slab`,
                `tfc:rock/cobble/${stone}_wall`,
                `tfc:rock/mossy_cobble/${stone}_stairs`,
                `tfc:rock/mossy_cobble/${stone}_slab`,
                `tfc:rock/mossy_cobble/${stone}_wall`
            ])
        event.add("tfc:can_start_collapse", 
            [
                `tfc:rock/cobble/${stone}_stairs`,
                `tfc:rock/cobble/${stone}_slab`,
                `tfc:rock/cobble/${stone}_wall`,
                `tfc:rock/mossy_cobble/${stone}_stairs`,
                `tfc:rock/mossy_cobble/${stone}_slab`,
                `tfc:rock/mossy_cobble/${stone}_wall`
            ])
        event.add("tfc:can_trigger_collapse", 
            [
                `tfc:rock/cobble/${stone}_stairs`,
                `tfc:rock/cobble/${stone}_slab`,
                `tfc:rock/cobble/${stone}_wall`,
                `tfc:rock/mossy_cobble/${stone}_stairs`,
                `tfc:rock/mossy_cobble/${stone}_slab`,
                `tfc:rock/mossy_cobble/${stone}_wall`
            ])
        event.add("tfc:can_landslide", 
            [
                `tfc:rock/cobble/${stone}_stairs`,
                `tfc:rock/cobble/${stone}_slab`,
                `tfc:rock/cobble/${stone}_wall`,
                `tfc:rock/mossy_cobble/${stone}_stairs`,
                `tfc:rock/mossy_cobble/${stone}_slab`,
                `tfc:rock/mossy_cobble/${stone}_wall`
            ])
        event.add("tfc:not_solid_supporting", 
            [
                `tfc:rock/cobble/${stone}_stairs`,
                `tfc:rock/cobble/${stone}_slab`,
                `tfc:rock/cobble/${stone}_wall`,
                `tfc:rock/mossy_cobble/${stone}_stairs`,
                `tfc:rock/mossy_cobble/${stone}_slab`,
                `tfc:rock/mossy_cobble/${stone}_wall`
            ])
    })
}