// priority 10

let ieRecipesRemoval = (/** @type {Internal.RecipesEventJS} */ event) => {
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:cokebrick" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:slab_cokebrick" })
  // event.remove({ mod: "immersiveengineering", output: "immersiveengineering:blastbrick" })
  // event.remove({ mod: "immersiveengineering", output: "immersiveengineering:blastbrick_reinforced" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:blastfurnace_preheater" })
  // event.remove({ mod: "immersiveengineering", output: "immersiveengineering:slab_blastbrick" })
  // event.remove({ mod: "immersiveengineering", output: "immersiveengineering:slab_blastbrick_reinforced" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:fertilizer" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:cloche" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:waterwheel_segment" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:windmill_base" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:watermill" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:windmill" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:sample_drill" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:dynamo" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:wooden_barrel" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:crafting_table" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:crate" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:reinforced_crate" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:coal_coke" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:dust_coke" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:coke" })
  event.remove({ mod: "immersiveengineering", output: "immersiveengineering:slab_coke" })

  event.remove({ mod: "immersiveengineering", id: /^immersiveengineering:.*_hammering/})
  event.remove({ mod: "immersiveengineering", id: /^immersiveengineering:crafting\/raw_hammercrushing.*/})
  event.remove({ mod: "immersiveengineering", id: /^immersiveengineering:crafting\/hammercrushing.*/})

  event.remove({ mod: "immersiveengineering", id: /^immersiveengineering:fermenter\/.*/})
  event.remove({ mod: "immersiveengineering", id: /^immersiveengineering:mixer\/.*/})
  event.remove({ mod: "immersiveengineering", id: /^immersiveengineering:squeezer\/.*/})

  event.remove({ id: "immersiveengineering:crafting/survey_tools"})
  event.remove({ id: "immersiveengineering:crafting/string"})
  event.remove({ id: `/^immersiveengineering:crafting\/pickaxe_.*/`})
  event.remove({ id: `/^immersiveengineering:crafting\/axe_.*/`})
  event.remove({ id: `/^immersiveengineering:crafting\/shovel_.*/`})
  event.remove({ id: `/^immersiveengineering:crafting\/sword_.*/`})
  event.remove({ id: `/^immersiveengineering:crafting\/hoe_.*/`})
  event.remove({ id: `/^immersiveengineering:crafting\/stick_.*/`})
  event.remove({ id: "immersiveengineering:crafting/wirecutter"})
  event.remove({ id: "immersiveengineering:crafting/craftingtable"})
  event.remove({ id: "immersiveengineering:crafting/workbench"})
  event.remove({ id: "immersiveengineering:crafting/ersatz_leather"})
  event.remove({ id: "createaddition:pressing/constantan_ingot"})
  event.remove({ id: "createaddition:compat/immersiveengineering/item_application/kiln_brick"})
  event.remove({output: `/^immersiveengineering:plate_.*/`, input: "immersiveengineering:wirecutter"})
  event.remove({ id: "createaddition:compat/immersiveengineering/item_application/kiln_brick"})
  event.remove({ id: "createaddition:compat/immersiveengineering/item_application/kiln_brick_using_deployer"})

  // IE Crusher: c:raw_materials/* → dust conflicts with IG↔GT raw ore conversion
  event.remove({ id: /^immersiveengineering:crusher\/raw_ore_.*/ })

  event.remove({ id: "immersiveengineering:refinery/biodiesel" })
}
